---
- name: Prelim Exam all VMs
  hosts: all

  tasks:
  - name: Change motd saying Ansible Managed by "student number"
    lineinfile:
      path: '/etc/motd'
      line: 'Ansible Managed by 1812699'
      state: present

  - name: Create a user with github username
    user:
      name: avtusing-tip
      state: present
      password: PrelimExam

  - name: passwordless sudo user
    lineinfile:
      path: '/etc/sudoers'
      line: 'avtusing-tip ALL=(ALL) NOPASSWD: ALL'
      state: present

  - name: group sysad2 
    group:
      name: sysad2
      state: present

  - name: add epel release repository
    dnf:
      name: epel-release
      state: latest

  - name: install htop
    dnf:
      name: htop
      state: latest
